<?php

namespace App\UI\User;

use App\DataModels\Support\DataModel;
use App\UI\XmlModel;

class UserModel extends XmlModel {
    protected $dataModelClass = UserDataModel::class;
    protected $xmlFileName = 'users';

    protected string $idProp = 'username';

    public function getByApiToken(string $apiToken) : ?UserDataModel{
        $items = $this->loadItemsFromXml('apiToken');

        return $items[$apiToken] ?? null;
    }

    public function prepareData(DataModel|array $data) {
        $password = $data['password'] ?? '';

        $passwordHashed = !is_null(password_get_info($password)['algo']);

        if(!$passwordHashed){
            $data['password'] = $password ? password_hash($password, PASSWORD_DEFAULT) : 'not_set';
        }

        return $data; // TODO: Change the autogenerated stub
    }
}
